fromString: add option to parse string with lat first
conveyal/lonlat pull request #13
Opened 2017-03-07 23:54 UTC by evansiroky

2017-03-08 00:24 UTC, landonreed requested changes
Just a couple of minor things.

2017-03-08 00:24 UTC, landonreed commented on index.js
> + * @param  {boolean} [latIsFrist=false] Whether or not the first value is latitude.
@evansiroky, I found a sneaky typo `latIsFrist`.  Might want to do a replaceAll

2017-03-08 00:24 UTC, landonreed commented on index.test.js
>        description: 'String with comma separating lon and lat'
Might be worth adding `, respectively` to this description and the one below for even more clarity.

2017-03-08 00:33 UTC, landonreed approved these changes

2017-03-08 00:35 UTC, merged

2017-03-08 12:56 UTC, trevorgerhardt commented
@evansiroky & @landonreed we should think more about this implementation. If we *know* lat is first then I would say we should consider it a new form or structure. This library is meant to be as explicit as possible (hence all the functions already). I would rather not add options to the conversion functions and rather explicitly create a new function called `fromLatFirstString` to be used in this instance.

2017-03-08 14:40 UTC, trevorgerhardt commented
`fromLatLonString` would also work.

2017-03-08 14:40 UTC, trevorgerhardt commented
But `fromLatFirstString` is more explicit

2017-03-09 06:13 UTC, evansiroky commented
See #14