Add table of contents to API
conveyal/lonlat pull request #8
Opened 2017-02-23 22:37 UTC by evansiroky

2017-02-24 09:58 UTC, trevorgerhardt requested changes

2017-02-24 09:58 UTC, trevorgerhardt commented on README.md
> +var str = lonlat.toString({ lat: 12, lng: 34 })   // '12,34'
Always use `lon`

2017-02-24 09:58 UTC, trevorgerhardt commented on README.md
> +var str = lonlat.toString({ lat: 12, lng: 34 })   // '12,34'
Especially in the docs

2017-02-24 09:59 UTC, trevorgerhardt commented
@evansiroky we really should be using a documentation generator for these libraries. This would all be automated.

2017-02-28 01:48 UTC, evansiroky commented
Closing in favor of #10

2017-02-28 01:48 UTC, closed without merging